
[
	Exposed = Window
] interface HubbleNode : EventTarget {

	// Message API
	void sendMessage([DefaultValue = Undefined] optional HubbleXobj msg,
		[DefaultValue = Undefined] optional ApplicationCallback callback);
	void addEventListener(DOMString eventName, ApplicationCallback callback);
	void addEventListener(DOMString subObjName, DOMString eventName, ApplicationCallback callback);
	void removeEventListener(DOMString eventName);

	void GetControlsNames(ApplicationCallback callback);
	void SyncCtrlTextChange(DOMString strcontrols, [DefaultValue = Undefined] optional ApplicationCallback callback);

	//Control Bind Api:
	void setControlVal(DOMString CtrlID, long long CtrlHandle, DOMString strVal);

	//Node API
	HubbleNode getChild(long nIndex);
	HubbleNode getChild(long row, long col);
	HubbleNode getChild(DOMString strName);
	void Observe(DOMString strKey, DOMString xml, [DefaultValue = Undefined] optional ApplicationCallback callback);
	void ObserveEx(DOMString strKey, DOMString xml, [DefaultValue = Undefined] optional long row, [DefaultValue = Undefined] optional long col, [DefaultValue = Undefined] optional ApplicationCallback callback);

	readonly attribute long row;
	readonly attribute long col;
	readonly attribute long rows;
	readonly attribute long cols;
	readonly attribute long long handle;
	readonly attribute long long hwnd;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleXobj xobj;
	readonly attribute DOMString name;
	readonly attribute DOMString objtype;

	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode root;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleNode parentGrid;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleWindow parentWindow;
	[RuntimeEnabled = TrustedDOMTypes, Replaceable] readonly attribute HubbleWinform parentForm;

	// Event handler attributes
	attribute EventHandler onMessageReceived;
	attribute EventHandler onGridCreated;
	attribute EventHandler onHubbleControlCreated;
	attribute EventHandler onMdiChildActivate;
	attribute EventHandler onWinFormCreated;
	attribute EventHandler onWinFormClosed;
};
